### ISSUE TITLE
Flix

### ISSUE THREAD

**Issue by ohmichael** [i96751414/plugin.video.flix#5]
I’ve tested this as an IMDb viewer and it’s great but I installed the rest of your programs & dependencies and your provider won’t resolve movies to the torrent player you got. I’m using kodi 18.9 leia. It’s one of the greats from using it so far.

**Comment by i96751414** [comment]
That's expected as the provider (https://github.com/i96751414/script.flix.magneto) as is is not configured with any parsers/scrapers (due to legal reasons).
I can tell you that configuring it is extremely easy, you just need to follow the examples provided in https://github.com/i96751414/script.flix.magneto/blob/master/README.md

**Comment by ohmichael** [comment]
That’s confusing but I’ll try it later what would be easier is making a provider manager to let you find providers and sync them with a file or url.
